### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by ash-rain** [limtaesu/alloworigin#14]
Have you made CPU/memory benchmarks? The code seems well-written and the fact that it's written in Python/Django leads me to believe it should be good at performance. However, it would be great if somebody shared some numbers.

**Comment by limtaesu** [comment]
Hi,

Since this project was a hobby project, I didn't think of doing CPU/mem benchmarks.
Off the top of my head, I can only think of the bottleneck being the connection to the request destination (requests lib). Other than that, I don't do any heavy operations. 

If you wish, you can come up with the numbers and share it here, so I can post it on readme.md
